Upgrade issue templates to the new issue template format
appwrite/sdk-for-ruby pull request #5
Opened 2021-10-01 14:44 UTC by MatteoGheza

Closes #4
Issue examples:
Feature request: https://github.com/MatteoGheza/sdk-for-ruby/issues/3
Documentation update request: https://github.com/MatteoGheza/sdk-for-ruby/issues/4
Bug report: https://github.com/MatteoGheza/sdk-for-ruby/issues/6

2021-10-03 10:23 UTC, lohanidamodar commented
@MatteoGheza Great work. One more change before we can approve. We have made few changes in the language and also the format of Code of conduct. Please check https://github.com/appwrite/appwrite template and update accordingly.
Thank you.

2021-10-03 14:29 UTC, MatteoGheza commented
@lohanidamodar done.
BTW I found a typo in https://github.com/appwrite/appwrite/blob/master/.github/ISSUE_TEMPLATE/bug.yaml (line 61) so i opened a PR.
[](https://github.com/appwrite/appwrite/pull/1866)

2021-10-04 07:12 UTC, lohanidamodar requested changes
@MatteoGheza Great work. For now we want some few changes to make it consistent across repositories.
Thank you 👍🏻

2021-10-04 07:12 UTC, lohanidamodar commented on .github/ISSUE_TEMPLATE/bug.yaml
> +      label: "📜 Example code for reproducing this bug"
Lets keep it consistent across other repositories. This info can be included in the reproduction steps.

2021-10-04 07:12 UTC, lohanidamodar commented on .github/ISSUE_TEMPLATE/bug.yaml
> +      label: "🎲 Appwrite SDK for Ruby version"
Same here, let's keep it consistent at the moment.

2021-10-04 07:16 UTC, MatteoGheza commented
Done.

2021-10-06 12:01 UTC, christyjacob4 approved these changes

2021-10-06 12:01 UTC, merged